# Generated by Django 3.2.8 on 2021-12-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charityID', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('cardNumber', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=500)),
                ('phonenumber', models.CharField(max_length=500)),
                ('authusers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
                ('reqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.request')),
            ],
        ),
    ]
