# Generated by Django 3.2.8 on 2021-12-11 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqID', models.IntegerField(default=0)),
                ('createDate', models.DateTimeField(default=datetime.datetime(2021, 12, 11, 21, 14, 1, 514059, tzinfo=utc))),
                ('closeDate', models.DateTimeField(default=datetime.datetime(2021, 12, 11, 21, 14, 1, 514081, tzinfo=utc))),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.CharField(default='', max_length=200)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
    ]
